baseURL = "https://smithjw.me"
languageCode = "en-us"
title = "james' ubiquitous blog"
# disablePathToLower = true
paginate = 8

[module]
    [[module.imports]]
        path = "github.com/lukeorth/poison"

[Params]
    brand = "James Smith"                               # name of your site - appears in the sidebar
    brand_image = "/images/me.png"                      # path to the image shown in the sidebar
    dark_mode = true
    description = "a site about everything and nothing"
    favicon = "/icons/favicon.ico"

    menu = [
        { Name = "About", URL = "/about/", HasChildren = false },
        { Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 3 },
    ]

    [Params.comment.fediverse]
        host = "mastodon.social"
        user = "smithjw"

[[Params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/smithjw"
[[Params.social]]
    icon = "mastodon"
    name = "Mastodon"
    url = "https://mastodon.social/@Smithjw"
[[Params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/smithjw87"

[[Params.social]]
    icon = "slack"
    name = "Mac Admins Slack"
    url = "https://macadmins.slack.com/messages/D1PELKDFT/team/U1PEQKG9Y/"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 3
    [[menu.main]]
        identifier = "cv"
        name = "CV"
        url = "/cv/"
        weight = 4
    [[menu.main]]
        identifier = "lego"
        name = "LEGO"
        url = "/lego/"
        weight = 4

[markup.goldmark.renderer]
    unsafe = true
