baseURL = "https://smithjw.me/"
languageCode = "en-us"
paginate = 8
title = "james' ubiquitous blog"

[Author]
    email = "james@smithjw.me"
    name = "James Smith"

[outputFormats]
    [outputFormats.RSS]
        baseName = "feed"
        mediatype = "application/rss"

[module]
    [[module.imports]]
        path = "github.com/lukeorth/poison"
    [[module.imports]]
        path = "github.com/AlanTanner/pdfjs-hugo-module"
[menu]
    [[menu.main]]
        identifier = 'posts'
        name = 'Posts'
        url = '/posts/'
        weight = 1
    [[menu.main]]
        identifier = 'cv'
        name = 'CV'
        url = '/cv/'
        weight = 2

[Params]
    brand = "James Smith"
    brand_image = "/images/me.png"
    dark_mode = true
    description = "a site about everything and nothing"
    favicon = "/icons/favicon.ico"

    github_url = "https://github.com/smithjw"
    linkedin_url = "https://www.linkedin.com/in/smithjw87"
    mastodon_url = "https://mastodon.social/@Smithjw"
    slack_url = "https://macadmins.slack.com/messages/D1PELKDFT/team/U1PEQKG9Y/"
    twitter_url = "https://twitter.com/smithjw"

    menu = [
        { Name = "Content", URL = "/content/", HasChildren = true },
        { Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 3 },
    ]

    [Params.comment.fediverse]
        host = "mastodon.social"
        user = "smithjw"

[markup.goldmark.renderer]
    unsafe = true
