baseURL = "https://smithjw.me"
languageCode = "en-us"
title = "james' ubiquitous blog"
theme = "m10c"
disablePathToLower = true
css = "/css/style.css"

[Params]
author = "James Smith"
description = "Short description of the author"
avatar = "images/me.png"
favicon = "icons/favicon.ico"
[Params.comment]
[Params.comment.fediverse]
host = "mastodon.social"
user = "smithjw"
